FROM golang:1.19.2 as BUILD

WORKDIR /project

RUN go install honnef.co/go/tools/cmd/staticcheck@latest

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

ENTRYPOINT ["make", "dockertest"]



